pkg/dronereceiver/handler.go

Split error when build info is nil and when there is no `build.Finished` field in place

`grafana-ci-otel-collector`: Split error for better handling

---

config/manifest.yaml

Adds healthcheckextension to add `/health` endpoint in the collector config

`cicd-o11y`: Add healthcheckextension

---

config/manifest.yaml

Updates the GHA receiver to 94f67035aacc07804e3422b8eb6713f6abaec0f9 (https://github.com/grafana/opentelemetry-collector-contrib/commit/94f67035aacc07804e3422b8eb6713f6abaec0f9)

update gha receiver

---

.github/workflows/ci.yml

Need login-to-gar using the prod environment to pull from `grafanalabs-global` repos.

CI/CD: Login to `prod` GAR to pull from updater

---

Makefile
receiver/githubactionsreceiver/config_test.go
receiver/githubactionsreceiver/documentation.md
receiver/githubactionsreceiver/factory.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics_test.go
receiver/githubactionsreceiver/metadata.yaml

in https://github.com/grafana/grafana-ci-otel-collector/pull/130, queue metrics were wrongly defined as delta while they were in fact cumulative (besides from preventing `prometheusremotewrite` to process them, see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md)
> ⚠️ Non-cumulative monotonic, histogram, and summary OTLP metrics are dropped by this exporter.
It also includes the fixes in https://github.com/grafana/grafana-ci-otel-collector/pull/131/ to create a default metrics builder config, without this change metrics needed to be enabled manually while the documentation stated otherwise.

fix: make metrics cumulative

---

receiver/githubactionsreceiver/metric_event_handling.go

This PR should workaround the issues of using counters when their values do not reset at the same time.
By forcefully reset all other possible statuses for a given set of repo/label to 0, we forcefully reset all of them at the same time, avoiding delayed resets that cause huge spikes.
The current value for jobs in a given status is `job{status=OBSERVED_STATUS} - job{status=NEXT_STATUS}`
T0:
```
jobs{status=queued} 1001
jobs{status=in_progress} 1000
```
(actual jobs in `queued` state is `1001 - 1000 = 1`)
T1 (after the collector restarts and an `in_progress` event is received):
```
jobs{status=in_progress} 1
```
At this point, prometheus will have the current state internally:
```
jobs{status=queued} 1001
jobs{status=in_progress} 1
```
so until another `queued` event is received, and the …

fix: handle delayed resets by forcefully recording 0s for unreceived events

---

receiver/githubactionsreceiver/metric_event_handling.go
receiver/githubactionsreceiver/receiver.go
receiver/githubactionsreceiver/receiver_test.go

Follow up to https://github.com/grafana/grafana-ci-otel-collector/pull/144
Add tests for the metrics event handling. the test should make sure that for a given status, datapoints are registered also for all other statuses.

chore: add event to metrics tests

---

.github/workflows/ci.yml

Follow up to https://github.com/grafana/deployment_tools/pull/177955
The way the image updater is set up causes merge conflicts on the images file because 2 PRs are created from the same base and touch the same file, one for `ops` and one for `dev` (automerged).
By moving those to separate files we should be able to avoid those merge conflicts.

ci: change updater images paths

---

receiver/githubactionsreceiver/documentation.md
receiver/githubactionsreceiver/generated_component_test.go
receiver/githubactionsreceiver/generated_package_test.go
receiver/githubactionsreceiver/internal/metadata/generated_config_test.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics_test.go
receiver/githubactionsreceiver/internal/metadata/generated_status.go
receiver/githubactionsreceiver/metadata.yaml
receiver/githubactionsreceiver/metric_event_handling.go

Adds `aborted` status, which is when a workflow starts but gets cancelled before the job is set up. 
This workflow goes straight from `queued` status to `complete`, without being in progress.

[WIP] Add aborted job status

---

go.mod
go.sum
receiver/githubactionsreceiver/documentation.md
receiver/githubactionsreceiver/internal/metadata/generated_metrics.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics_test.go
receiver/githubactionsreceiver/metadata.yaml
receiver/githubactionsreceiver/metric_event_handling.go

Followup to https://github.com/grafana/grafana-ci-otel-collector/pull/178. After adding this label in the span metric, it would also be useful to add it in the `workflow.jobs.count` metric in which we can also play around with workflow conclusions and statuses.
Reason why it doesn't _really_ work in #178 is because the status code which is provided there, is the status code of the span and not the status code of the workflow.

feat: add `ci.github.workflow.job.head_branch.is_main` to `workflow.jobs.count` metric

---

receiver/dronereceiver/README.md
receiver/dronereceiver/metadata.yaml
receiver/githubactionsreceiver/README.md
receiver/githubactionsreceiver/metadata.yaml

Adds `dsotirakis` handle in the `githubactionsreceiver` and `dronereceiver` codeowners section.

chore: Add dsotirakis as codeowner in the receivers

---

receiver/githubactionsreceiver/metric_event_handling.go

These logs are not needed and should be only available on the debug level instead. We used them when we were trying to figure out the queues calculation.

chore: change log levels for event logging

---

.github/workflows/ci.yml

We have caching for the Go toolchain and dependencies at the minute. But the cache key is the hash of the `go.sum` file, and so the cache isn't used whenever this is updated.
CI can take up to 10 minutes to run, a decent chunk of which is installing dependencies. When we get a lot of Dependabot bumps at once it can be a bit tedious to have to wait for all of them, especially when they need to rebase multiple times.
The `actions/cache` action which we use has a `restore-keys` option, which allows us to specify a list of keys to use when restoring cache. You write your cache key as a hierarchy, and the action will restore the closest one which matches.
This means in our case we include the runner OS and CPU architecture in the key. If the exact match isn't found, we restore the latest cache …

ci(go): restore inexact go caches

---

Makefile
go.mod
go.sum
receiver/githubactionsreceiver/documentation.md
receiver/githubactionsreceiver/go.mod
receiver/githubactionsreceiver/go.sum
receiver/githubactionsreceiver/internal/metadata/generated_config.go
receiver/githubactionsreceiver/internal/metadata/generated_config_test.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics.go
receiver/githubactionsreceiver/internal/metadata/generated_metrics_test.go
receiver/githubactionsreceiver/internal/metadata/testdata/config.yaml
receiver/githubactionsreceiver/metadata.yaml
receiver/githubactionsreceiver/metric_event_handling.go

Adding `cicd_o11y_build_info` metric, to use an automated CD process in Argo Workflows.
Since our collector uses `prometheusexporter`, we cannot use native prometheus here and we should expose this metric using the otel collector itself.
Part of: https://github.com/grafana/deployment_tools/issues/249739
------
Working example, after trying on dev:

self-metrics: Add `cicd_o11y_build_info` metric

---

.github/workflows/ci.yml
receiver/githubactionsreceiver/trace_attributes.go

This will extract an ec2 instance id from Grafana's self-hosted runner's if the runner's group name is set to "default" (case insensitive). 
Goes with https://github.com/grafana/deployment_tools/pull/251705

feat: add ec2 instance id to GitHub trace metrics

---

receiver/githubactionsreceiver/trace_attributes.go

We've modified our dev GitHub hosted runners to use the group "Self-hosted" instead of "Default". This is to match that change.

chore: update gh-runner group names to match new group for dev

---

go.mod
receiver/githubactionsreceiver/go.mod

Noticed there are multiple and that shouldn't happen. I think that `go mod tidy` has an issue which sometimes does this but I've never managed to make it happen reliably.

chore(build): consolidate duplicate replace sections in `go.mod`

---

config/manifest.yaml

Adding `otlphttpexporter` to our manifest dependencies for use in the the cicd-o11y logs ingestion pipeline following deprecation of the loki exporter
Source issue: https://github.com/grafana/deployment_tools/issues/231125

feat: Add otlphttp 0.120.0 dependency

---

config/manifest.yaml

Allow users to enable pprof while running the collector, allowing profiles to be produced & scraped.

fix: add pprof extension

---

.github/workflows/ci.yml

Ran `zizmor` on `main` and applied its suggestions- aside from a few about "credential persistence through GitHub Actions artifacts", which _looks_ to be necessary, but I wouldn't mind another set of eyes verifying that.

ci: apply zizmor suggestions

---

config/manifest.yaml

Leftover after: https://github.com/grafana/grafana-ci-otel-collector/pull/257

deps: bump `otlphttp` exporter to 0.125.0

---

.github/workflows/ci.yml

The CI was refactored in d29cd39644c2151fa22b1cfc0f21ee727ce7717f to put deploying into a separate job. That's fine, but the job didn't have `id-token: write` permissions - here we add those.
Also noticed while here that the "Export GHA URL" and "Get Vault secrets" steps are unused. We can delete those.

fix(ci): add OIDC permission for deploy job, delete unused steps

---

receiver/githubactionsreceiver/metric_event_handling.go

We were getting messages like: 
`collected metric 'cicd_o11y_workflow_jobs_count' was collected before with the same name and label values`
or
`failed to convert metric workflow.jobs.count: duplicate label names in constant and variable labels for metric \"cicd_o11y_workflow_jobs_count\""`
This occurred because the OpenTelemetry MetricsBuilder was receiving multiple data points with identical label combinations within a single emission cycle.
Fixed it using a `sync.Map` and created unique keys for each metric combination so it can only record each unique combination once per emission.
Tested on dev, no such errors in the last 12h.

bug: fix workflow.jobs.count duplication

---

.github/workflows/ci.yml

Updates `shared-workflows` `push-to-gar-docker` and `trigger-argo-workflows` actions to their latest versions.

ci: update shared-workflows actions to latest pinned versions

---

receiver/githubactionsreceiver/trace_event_handling.go

This PR aims to further reduce logging at info level to optimise memory usage in ops
WF job and run events for traces are running at info level, so this change modifies to debug in line with our log event handling [source](https://github.com/grafana/grafana-ci-otel-collector/blob/7c75d22158223689501c5f89744491a1f1f3b7ca/receiver/githubactionsreceiver/log_event_handling.go#L50C24-L50C40)

Modify trace event workflow run&job events log level to debug

---

.github/renovate.json

These are not necessary since we have replace statements in place.
Related to https://github.com/grafana/grafana-ci-otel-collector/pull/349

ci: disable updates of internal references

---

.github/renovate.json
docker-compose.yml

These dependencies should just stick to latest without the need to constantly getting re-pinned when upstream changes.

chore: do not update docker-compose.yml
